name: flutter_sandbox
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  camera: ^0.5.7+4
  cupertino_icons: ^0.1.2
  firebase_core: ^0.2.5
  firebase_analytics: ^1.0.4
  flutter:
    sdk: flutter
  path: ^1.6.4
  path_provider: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
